pixels:
  x0: 799.5                 # Origin x
  y0: 599.5                 # Origin y
  xs: 4.4                   # Pixel width in µm
  ys: 4.4                   # Pixel height in µm

detector:
  xres: 1600
  yres: 1200
  noise:
    distribution: 'normal'
    parameters:
      sigma: 3
      mean: 10

padding:
  start: 0.5
  end: 0.5